import React from 'react';
import { Bar } from 'react-chartjs-2';

export default function BarChart() {
    const data = {
        labels: [
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
            '22',
            '23',
            '24',
        ],
        datasets: [
            {
                label: 'Today',
                data: [
                    6,
                    6,
                    7,
                    5,
                    7,
                    7,
                    6,
                    5.5,
                    6.5,
                    5.5,
                    7,
                    6.5,
                    5.8,
                    5.5,
                    6.5,
                    7,
                    7,
                    6.5,
                    7,
                    5.8,
                ],
                borderColor: [
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                ],
                backgroundColor: [
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                    '#5a9bd4',
                ],
            },
            {
                label: 'Yesterday',
                data: [
                    6,
                    6,
                    7,
                    6,
                    7,
                    7,
                    7.5,
                    7,
                    7.5,
                    7,
                    6.5,
                    6.8,
                    6,
                    5,
                    6,
                    5,
                    5.5,
                    6.8,
                    5.8,
                    5,
                    6.8,
                    6.2,
                    5.5,
                    8,
                ],
                borderColor: [
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                ],
                backgroundColor: [
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                    '#ee7e2f',
                ],
            },
        ],
    };

    const options = {
        title: {
            display: true,
            text: 'Litres',
            position: 'left',
        },
        maintainAspectRatio: false,
        legend: {
            display: true,
            position: 'bottom',
        },
        scales: {
            yAxes: [
                {
                    ticks: {
                        min: 0,
                        max: 8,
                        stepSize: 2,
                    },
                    gridLines: {
                        drawBorder: false,
                    },
                },
            ],
            xAxes: [
                {
                    gridLines: {
                        display: false,
                    },
                    barPercentage: 0.7,
                },
            ],
        },
    };

    return (
        <div>
            <Bar data={data} height={null} width={null} options={options} />
        </div>
    );
}
